CATEGORIES = {

        "study": [
            "study", "studies", "studying",
            "exam", "exams", "test", "tests",
            "quiz", "quizzes",
            "focus", "concentrate", "concentration",
            "college", "school", "university",
            "campus", "class", "classes",
            "lecture", "lectures",
            "teacher", "professor",
            "learn", "learning",
            "subject", "subjects",
            "marks", "grade", "grades",
            "cgpa", "gpa", "percentage",
            "syllabus", "chapter", "chapters",
            "assignment", "assignments",
            "homework", "project", "projects",
            "presentation", "presentations",
            "education", "academic", "academics",
            "revision", "revise",
            "memory", "memorize",
            "concept", "concepts",
            "notes", "notebook",
            "preparation", "preparing",
            "semester", "rank", "ranking",
            "performance", "lab",
            "practical", "tutorial",
            "doubt", "understand",
            "understanding", "course",
            "courses"
        ],

        "career": [
            "job", "jobs",
            "career", "future",
            "interview", "interviews",
            "resume", "cv",
            "salary", "package",
            "work", "working",
            "employment", "employer",
            "employee", "profession",
            "professional", "occupation",
            "office", "workplace",
            "promotion", "manager",
            "management", "boss",
            "company", "organization",
            "startup", "business",
            "internship", "intern",
            "placement", "placements",
            "recruiter", "recruitment",
            "hiring", "vacancy",
            "opening", "application",
            "applying", "offer",
            "income", "earning",
            "earnings", "pay",
            "skill", "skills",
            "upskill", "certification",
            "certificate", "linkedin",
            "freelance", "freelancing",
            "remote", "confused",
            "direction", "path",
            "choose", "decision"
        ],

        "health": [
            "health", "healthy",
            "unhealthy",
            "sleep", "sleeping",
            "insomnia", "rest",
            "stress", "stressed",
            "stressful",
            "anxiety", "anxious",
            "panic", "panicking",
            "nervous",
            "worried", "worry",
            "mental", "physical",
            "fitness", "fit",
            "exercise", "workout",
            "gym", "diet",
            "nutrition", "meal",
            "meals", "food",
            "eating", "weight",
            "body", "doctor",
            "hospital", "medicine",
            "treatment", "therapy",
            "fatigue", "exhaustion",
            "burnout", "depression",
            "headache", "migraine",
            "pain", "injury",
            "illness", "disease",
            "fever", "cold",
            "cough", "breathing",
            "recovery", "hydration",
            "water", "energy",
            "tired"
        ],

        "productivity": [
            "lazy", "laziness",
            "procrastinate", "procrastination",
            "delay", "postpone",
            "phone", "mobile",
            "instagram", "youtube",
            "facebook", "snapchat",
            "whatsapp", "telegram",
            "reels", "shorts",
            "scrolling", "scroll",
            "distraction", "distracted",
            "productive", "productivity",
            "waste", "time",
            "routine", "habit",
            "consistency", "consistent",
            "goal", "goals",
            "target", "targets",
            "planning", "plan",
            "organize", "organization",
            "schedule", "calendar",
            "deadline", "deadlines",
            "priority", "priorities",
            "discipline",
            "motivation", "motivated",
            "demotivated", "unmotivated",
            "multitasking", "workflow",
            "task", "tasks",
            "progress", "tracking",
            "achievement", "achieve",
            "accomplish", "effort"
        ]
    }
VALID_CATEGORIES = {
    "study",
    "career",
    "productivity",
    "health"
}
