CAUSES = {

        "phone_addiction": [
            "phone", "mobile", "smartphone",
            "android", "iphone", "device",
            "screen", "screentime",
            "instagram", "youtube", "facebook",
            "snapchat", "whatsapp", "telegram",
            "twitter", "reddit", "discord",
            "social", "media",
            "reels", "shorts", "stories",
            "scroll", "scrolling",
            "feed", "binge", "video",
            "videos", "gaming", "games",
            "notification", "notifications",
            "chat", "chatting",
            "message", "messages",
            "online", "internet",
            "content",
            "streaming", "watching",
            "addicted", "addiction",
            "compulsive", "checking",
            "refreshing"
        ],

        "lack_of_focus": [
            "focus", "focused", "focusing",
            "concentrate", "concentrating",
            "concentration", "attention",
            "attentive",
            "distracted", "distraction",
            "mind", "mindset",
            "daydream", "daydreaming",
            "wander", "wandering",
            "overthinking",
            "thoughts", "thinking",
            "clarity",
            "learn", "learning",
            "reading", "revision",
            "memory", "remember",
            "memorize", "forget",
            "forgetting",
            "retention",
            "understand",
            "understanding",
            "deepwork",
            "interruptions",
            "noise",
            "bored",
            "boredom",
            "restless",
            "restlessness",
            "mental",
            "fatigue",
        ],

        "procrastination": [
            "lazy", "laziness",
            "delay", "delayed",
            "postpone", "postponing",
            "later", "tomorrow",
            "avoid", "avoiding",
            "procrastinate",
            "procrastinating",
            "pending",
            "unfinished",
            "uncompleted",
            "stuck",
            "unmotivated",
            "demotivated",
            "motivation",
            "discipline",
            "habit",
            "habits",
            "routine",
            "consistency",
            "task", "tasks",
            "deadline",
            "deadlines",
            "hesitation",
            "hesitate",
            "start",
            "starting",
            "begin",
            "beginning",
            "complete",
            "completion",
            "finish",
            "finishing",
            "effort",
            "wasting",
            "waste"
        ],

        "stress": [
            "stress",
            "stressed",
            "stressful",
            "anxiety",
            "anxious",
            "pressure",
            "pressured",
            "panic",
            "panicking",
            "worried",
            "worry",
            "burnout",
            "overwhelmed",
            "mental",
            "fatigue",
            "tired",
            "exhausted",
            "exhaustion",
            "overthinking",
            "headache",
            "migraine",
            "insomnia",
            "restless",
            "restlessness",
            "nervous",
            "nervousness",
            "overloaded",
            "overload",
            "frustrated",
            "frustration",
        ],

        "career_confusion": [
            "career",
            "future",
            "confused",
            "confusion",
            "direction",
            "path",
            "choose",
            "choice",
            "decision",
            "decide",
            "goal",
            "goals",
            "purpose",
            "ambition",
            "dream",
            "dreams",
            "interest",
            "interests",
            "passion",
            "field",
            "profession",
            "occupation",
            "job",
            "jobs",
            "work",
            "employment",
            "opportunity",
            "opportunities",
            "guidance",
            "mentor",
            "advice",
            "uncertain",
            "unsure",
            "lost",
            "switch",
            "change",
            "stream",
            "branch",
            "specialization",
            "major",
            "degree",
            "graduation",
            "placement",
            "interview",
            "resume",
            "skill",
            "skills",
            "upskill",
            "growth",
            "roadmap",
            "plan",
            "planning",
            "research",
            "researching",
            "explore",
            "exploration",
        ],

        "lack_of_energy": [
            "sleepy",
            "sleepiness",
            "tired",
            "fatigue",
            "fatigued",
            "exhausted",
            "exhaustion",
            "energy",
            "low energy",
            "drained",
            "weak",
            "drowsy",
            "lethargic",
            "burned out",
            "burnt out",
            "sleep",
            "sleeping",
            "rest",
            "restless",
            "no energy",
            "sluggish",
            "yawning",
            "drowsiness",
            "lack of sleep",
        ],
        
    }
VALID_CAUSES = {
    "lack_of_focus",
    "procrastination",
    "stress",
    "phone_addiction",
    "career_confusion",
    "lack_of_energy",
    "poor_sleep",
    "poor_nutrition",
    "lack_of_exercise",
    "low_confidence",
    "poor_time_management"
}