VOCABULARY = [
    "about",
    # =========================
    # Study
    # =========================
    "study",
    "education",
    "studying",
    "studies",
    "focus",
    "focused",
    "concentration",
    "concentrate",
    "exam",
    "exams",
    "assignment",
    "assignments",
    "homework",
    "college",
    "university",
    "school",
    "class",
    "lecture",
    "teacher",
    "professor",
    "subject",
    "subjects",
    "course",
    "courses",
    "education",
    "learning",
    "revision",
    "revise",
    "memorize",
    "memory",
    "notes",
    "notebook",
    "syllabus",
    "chapter",
    "chapters",
    "quiz",
    "quizzes",
    "semester",
    "cgpa",
    "gpa",
    "grade",
    "grades",
    "project",
    "projects",
    "presentation",
    "practical",
    "tutorial",
    "lab",
    "performance",

    # =========================
    # Career
    # =========================
    "career",
    "job",
    "jobs",
    "future",
    "interview",
    "interviews",
    "resume",
    "cv",
    "salary",
    "package",
    "work",
    "working",
    "profession",
    "professional",
    "company",
    "startup",
    "business",
    "internship",
    "intern",
    "placement",
    "placements",
    "recruitment",
    "recruiter",
    "hiring",
    "vacancy",
    "application",
    "offer",
    "income",
    "earning",
    "earnings",
    "promotion",
    "manager",
    "boss",
    "office",
    "employee",
    "employer",
    "skill",
    "skills",
    "upskill",
    "certification",
    "linkedin",
    "freelance",
    "remote",
    "future",
    "confused",
    "decision",
    "direction",
    "path",
    "choose",

    # =========================
    # Productivity
    # =========================
    "productivity",
    "productive",
    "lazy",
    "procrastinate",
    "procrastination",
    "delay",
    "postpone",
    "motivation",
    "motivated",
    "discipline",
    "consistency",
    "consistent",
    "habit",
    "habits",
    "routine",
    "goal",
    "goals",
    "target",
    "targets",
    "plan",
    "planning",
    "organize",
    "organization",
    "schedule",
    "calendar",
    "deadline",
    "deadlines",
    "priority",
    "priorities",
    "workflow",
    "task",
    "tasks",
    "achievement",
    "achieve",
    "accomplish",
    "progress",
    "tracking",
    "effort",
    "multitasking",
    "time",

    # =========================
    # Phone / Social Media
    # =========================
    "phone",
    "mobile",
    "instagram",
    "youtube",
    "facebook",
    "snapchat",
    "telegram",
    "whatsapp",
    "twitter",
    "reels",
    "reel",
    "shorts",
    "scrolling",
    "scroll",
    "social",
    "media",
    "addiction",
    "notification",
    "notifications",
    "screen",
    "screen time",

    # =========================
    # Health
    # =========================
    "health",
    "healthy",
    "sleep",
    "sleeping",
    "insomnia",
    "stress",
    "stressed",
    "anxiety",
    "anxious",
    "pressure",
    "panic",
    "nervous",
    "worried",
    "mental",
    "physical",
    "fitness",
    "exercise",
    "workout",
    "gym",
    "diet",
    "nutrition",
    "meal",
    "meals",
    "food",
    "weight",
    "doctor",
    "hospital",
    "medicine",
    "treatment",
    "therapy",
    "fatigue",
    "exhausted",
    "tired",
    "burnout",
    "depressed",
    "sad",
    "headache",
    "migraine",
    "pain",
    "injury",
    "illness",
    "disease",
    "fever",
    "cold",
    "cough",
    "breathing",
    "hydration",
    "water",
    "energy",
    "wasting",
    "too"
]
VALID_TAGS = {
    "student",
    "education",

    "career",
    "career_growth",
    "job_search",
    "resume",
    "interview",
    "work",

    "productivity",

    "health",
    "mental_health",

    "focus",
    "memory",
    "learning",

    "confidence",
    "communication",

    "motivation",
    "discipline",
    "habits",

    "stress",
    "anxiety",

    "phone",
    "social_media",
    "screen_time",

    "sleep",
    "nutrition",
    "exercise",
    "energy",

    "time_management",

    "planning",
    "organization",

    "performance",

    "skills",

    "projects",

    "environment",

    "posture",

    "workplace",

    "future",

    "wellness"
}
